[package]
name = "libre_pvz_resources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.1", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"], optional = true }
bevy = { version = "0.7", optional = true }
# below are dependencies already pulled in by bevy
anyhow = "1.0.55"
