[workspace]
members = [
    "optics",
    "libre_pvz",
    "libre_pvz_resources",
    "libre_pvz_animation",
    "reanim-decode",
]
resolver = "2"
exclude = ["bevy"]

[patch.crates-io]
bevy = { path = "bevy" }
