[workspace]
members = [
    "optics",
    "libre_pvz",
    "libre_pvz_resources",
    "libre_pvz_animation",
    "reanim-decode",
]
resolver = "2"

# https://bevy-cheatbook.github.io/pitfalls/performance.html
[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
