var sourcesIndex = JSON.parse('{\
"ab_glyph":["",[["ttfp",[],["outliner.rs","variable.rs"]]],["codepoint_ids.rs","err.rs","font.rs","font_arc.rs","glyph.rs","lib.rs","outlined.rs","scale.rs","ttfp.rs","variable.rs"]],\
"ab_glyph_rasterizer":["",[],["geometry.rs","lib.rs","raster.rs"]],\
"accesskit":["",[],["geometry.rs","lib.rs"]],\
"accesskit_winit":["",[["platform_impl",[],["mod.rs","null.rs"]]],["lib.rs"]],\
"adler":["",[],["algo.rs","lib.rs"]],\
"ahash":["",[],["convert.rs","fallback_hash.rs","hash_map.rs","hash_set.rs","lib.rs","operations.rs","random_state.rs","specialize.rs"]],\
"aho_corasick":["",[["packed",[["teddy",[],["compile.rs","mod.rs","runtime.rs"]]],["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]]],["ahocorasick.rs","automaton.rs","buffer.rs","byte_frequencies.rs","classes.rs","dfa.rs","error.rs","lib.rs","nfa.rs","prefilter.rs","state_id.rs"]],\
"alsa":["",[["direct",[],["ffi.rs","pcm.rs"]]],["card.rs","chmap.rs","ctl_int.rs","device_name.rs","direct.rs","error.rs","hctl.rs","io.rs","lib.rs","mixer.rs","pcm.rs","poll.rs","rawmidi.rs","seq.rs"]],\
"alsa_sys":["",[],["generated.rs","lib.rs"]],\
"anyhow":["",[],["backtrace.rs","chain.rs","context.rs","ensure.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","ptr.rs","wrapper.rs"]],\
"approx":["",[],["abs_diff_eq.rs","lib.rs","macros.rs","relative_eq.rs","ulps_eq.rs"]],\
"arboard":["",[["platform",[["linux",[],["mod.rs","x11.rs"]]],["mod.rs"]]],["common.rs","lib.rs"]],\
"arrayvec":["",[],["array_string.rs","arrayvec.rs","arrayvec_impl.rs","char.rs","errors.rs","lib.rs","utils.rs"]],\
"ash":["",[["extensions",[["experimental",[],["amd.rs","mod.rs"]],["ext",[],["acquire_drm_display.rs","buffer_device_address.rs","calibrated_timestamps.rs","debug_marker.rs","debug_report.rs","debug_utils.rs","descriptor_buffer.rs","extended_dynamic_state.rs","extended_dynamic_state2.rs","extended_dynamic_state3.rs","full_screen_exclusive.rs","headless_surface.rs","image_compression_control.rs","image_drm_format_modifier.rs","mesh_shader.rs","metal_surface.rs","mod.rs","physical_device_drm.rs","private_data.rs","sample_locations.rs","tooling_info.rs"]],["khr",[],["acceleration_structure.rs","android_surface.rs","buffer_device_address.rs","copy_commands2.rs","create_render_pass2.rs","deferred_host_operations.rs","device_group.rs","device_group_creation.rs","display.rs","display_swapchain.rs","draw_indirect_count.rs","dynamic_rendering.rs","external_fence_fd.rs","external_fence_win32.rs","external_memory_fd.rs","external_memory_win32.rs","external_semaphore_fd.rs","external_semaphore_win32.rs","get_memory_requirements2.rs","get_physical_device_properties2.rs","get_surface_capabilities2.rs","maintenance1.rs","maintenance3.rs","maintenance4.rs","mod.rs","pipeline_executable_properties.rs","present_wait.rs","push_descriptor.rs","ray_tracing_maintenance1.rs","ray_tracing_pipeline.rs","surface.rs","swapchain.rs","synchronization2.rs","timeline_semaphore.rs","wayland_surface.rs","win32_surface.rs","xcb_surface.rs","xlib_surface.rs"]],["mvk",[],["ios_surface.rs","macos_surface.rs","mod.rs"]],["nn",[],["mod.rs","vi_surface.rs"]],["nv",[],["coverage_reduction_mode.rs","device_diagnostic_checkpoints.rs","mesh_shader.rs","mod.rs","ray_tracing.rs"]]],["mod.rs"]],["vk",[],["aliases.rs","bitflags.rs","const_debugs.rs","constants.rs","definitions.rs","enums.rs","extensions.rs","feature_extensions.rs","features.rs","macros.rs","native.rs","platform_types.rs","prelude.rs"]]],["device.rs","entry.rs","instance.rs","lib.rs","prelude.rs","util.rs","vk.rs"]],\
"async_channel":["",[],["lib.rs"]],\
"async_executor":["",[],["lib.rs"]],\
"async_task":["",[],["header.rs","lib.rs","raw.rs","runnable.rs","state.rs","task.rs","utils.rs"]],\
"base64":["",[["read",[],["decoder.rs","mod.rs"]],["write",[],["encoder.rs","encoder_string_writer.rs","mod.rs"]]],["chunked_encoder.rs","decode.rs","display.rs","encode.rs","lib.rs","tables.rs"]],\
"bevy":["",[],["lib.rs"]],\
"bevy_a11y":["",[],["lib.rs"]],\
"bevy_animation":["",[],["lib.rs"]],\
"bevy_app":["",[],["app.rs","config.rs","lib.rs","plugin.rs","plugin_group.rs","schedule_runner.rs"]],\
"bevy_asset":["",[["diagnostic",[],["asset_count_diagnostics_plugin.rs","mod.rs"]],["io",[],["file_asset_io.rs","metadata.rs","mod.rs"]]],["asset_server.rs","assets.rs","filesystem_watcher.rs","handle.rs","info.rs","lib.rs","loader.rs","path.rs","reflect.rs"]],\
"bevy_asset_loader":["",[["loading_state",[],["dynamic_asset_systems.rs","systems.rs"]]],["asset_collection.rs","dynamic_asset.rs","lib.rs","loading_state.rs"]],\
"bevy_asset_loader_derive":["",[],["assets.rs","lib.rs"]],\
"bevy_audio":["",[],["audio.rs","audio_output.rs","audio_source.rs","lib.rs","sinks.rs"]],\
"bevy_core":["",[],["lib.rs","name.rs","task_pool_options.rs"]],\
"bevy_core_pipeline":["",[["blit",[],["mod.rs"]],["bloom",[],["downsampling_pipeline.rs","mod.rs","settings.rs","upsampling_pipeline.rs"]],["core_2d",[],["camera_2d.rs","main_pass_2d_node.rs","mod.rs"]],["core_3d",[],["camera_3d.rs","main_pass_3d_node.rs","mod.rs"]],["fullscreen_vertex_shader",[],["mod.rs"]],["fxaa",[],["mod.rs","node.rs"]],["prepass",[],["mod.rs","node.rs"]],["tonemapping",[],["mod.rs","node.rs"]],["upscaling",[],["mod.rs","node.rs"]]],["clear_color.rs","lib.rs","msaa_writeback.rs"]],\
"bevy_derive":["",[],["app_plugin.rs","bevy_main.rs","derefs.rs","enum_variant_meta.rs","lib.rs"]],\
"bevy_diagnostic":["",[],["diagnostic.rs","entity_count_diagnostics_plugin.rs","frame_time_diagnostics_plugin.rs","lib.rs","log_diagnostics_plugin.rs","system_information_diagnostics_plugin.rs"]],\
"bevy_ecs":["",[["entity",[],["map_entities.rs","mod.rs"]],["query",[],["access.rs","fetch.rs","filter.rs","iter.rs","mod.rs","par_iter.rs","state.rs"]],["schedule",[["executor",[],["mod.rs","multi_threaded.rs","simple.rs","single_threaded.rs"]]],["condition.rs","config.rs","graph_utils.rs","mod.rs","schedule.rs","set.rs","state.rs"]],["storage",[],["blob_vec.rs","mod.rs","resource.rs","sparse_set.rs","table.rs"]],["system",[["commands",[],["command_queue.rs","mod.rs","parallel_scope.rs"]]],["combinator.rs","exclusive_function_system.rs","exclusive_system_param.rs","function_system.rs","mod.rs","query.rs","system.rs","system_param.rs","system_piping.rs"]],["world",[],["entity_ref.rs","identifier.rs","mod.rs","spawn_batch.rs","unsafe_world_cell.rs","world_cell.rs"]]],["archetype.rs","bundle.rs","change_detection.rs","component.rs","event.rs","lib.rs","reflect.rs","removal_detection.rs"]],\
"bevy_ecs_macros":["",[],["component.rs","fetch.rs","lib.rs","set.rs","states.rs"]],\
"bevy_egui":["",[],["egui_node.rs","lib.rs","render_systems.rs","systems.rs"]],\
"bevy_encase_derive":["",[],["lib.rs"]],\
"bevy_gilrs":["",[],["converter.rs","gilrs_system.rs","lib.rs"]],\
"bevy_gltf":["",[],["lib.rs","loader.rs"]],\
"bevy_hierarchy":["",[["components",[],["children.rs","mod.rs","parent.rs"]]],["child_builder.rs","events.rs","hierarchy.rs","lib.rs","query_extension.rs","valid_parent_check_plugin.rs"]],\
"bevy_input":["",[],["axis.rs","common_conditions.rs","gamepad.rs","input.rs","keyboard.rs","lib.rs","mouse.rs","touch.rs"]],\
"bevy_inspector_egui":["",[["bevy_inspector",[],["errors.rs","hierarchy.rs","mod.rs"]],["inspector_egui_impls",[["image",[],["image_texture_conversion.rs"]]],["bevy_impls.rs","glam_impls.rs","image.rs","mod.rs","std_impls.rs"]],["inspector_options",[],["default_options.rs","mod.rs","std_options.rs"]],["reflect_inspector",[],["errors.rs","mod.rs"]]],["egui_utils.rs","lib.rs","quick.rs","restricted_world_view.rs","utils.rs"]],\
"bevy_inspector_egui_derive":["",[],["attributes.rs","lib.rs"]],\
"bevy_internal":["",[],["default_plugins.rs","lib.rs","prelude.rs"]],\
"bevy_log":["",[],["lib.rs"]],\
"bevy_macro_utils":["",[],["attrs.rs","lib.rs","shape.rs","symbol.rs"]],\
"bevy_math":["",[],["cubic_splines.rs","lib.rs","ray.rs","rect.rs"]],\
"bevy_mikktspace":["",[],["generated.rs","lib.rs"]],\
"bevy_pbr":["",[["environment_map",[],["mod.rs"]],["prepass",[],["mod.rs"]],["render",[],["fog.rs","light.rs","mesh.rs","mod.rs"]]],["alpha.rs","bundle.rs","fog.rs","lib.rs","light.rs","material.rs","pbr_material.rs","wireframe.rs"]],\
"bevy_prototype_lyon":["",[["render",[],["mod.rs"]]],["draw.rs","entity.rs","geometry.rs","lib.rs","path.rs","plugin.rs","shapes.rs","utils.rs","vertex.rs"]],\
"bevy_ptr":["",[],["lib.rs"]],\
"bevy_reflect":["",[["enums",[],["dynamic_enum.rs","enum_trait.rs","helpers.rs","mod.rs","variants.rs"]],["impls",[],["glam.rs","rect.rs","smallvec.rs","std.rs"]],["serde",[],["de.rs","mod.rs","ser.rs","type_data.rs"]]],["array.rs","fields.rs","from_reflect.rs","lib.rs","list.rs","map.rs","path.rs","reflect.rs","std_traits.rs","struct_trait.rs","tuple.rs","tuple_struct.rs","type_info.rs","type_registry.rs","type_uuid.rs","type_uuid_impl.rs","utility.rs"]],\
"bevy_reflect_derive":["",[["impls",[],["enums.rs","mod.rs","structs.rs","tuple_structs.rs","typed.rs","values.rs"]]],["container_attributes.rs","derive_data.rs","enum_utility.rs","field_attributes.rs","fq_std.rs","from_reflect.rs","lib.rs","reflect_value.rs","registration.rs","trait_reflection.rs","type_uuid.rs","utility.rs"]],\
"bevy_render":["",[["camera",[],["camera.rs","camera_driver_node.rs","mod.rs","projection.rs"]],["color",[],["colorspace.rs","mod.rs"]],["mesh",[["mesh",[],["conversions.rs","mod.rs","skinning.rs"]],["shape",[],["capsule.rs","cylinder.rs","icosphere.rs","mod.rs","regular_polygon.rs","torus.rs","uvsphere.rs"]]],["mod.rs"]],["primitives",[],["mod.rs"]],["render_graph",[],["context.rs","edge.rs","graph.rs","mod.rs","node.rs","node_slot.rs"]],["render_phase",[],["draw.rs","draw_state.rs","mod.rs","rangefinder.rs"]],["render_resource",[],["bind_group.rs","bind_group_layout.rs","buffer.rs","buffer_vec.rs","mod.rs","pipeline.rs","pipeline_cache.rs","pipeline_specializer.rs","resource_macros.rs","shader.rs","storage_buffer.rs","texture.rs","uniform_buffer.rs"]],["renderer",[],["graph_runner.rs","mod.rs","render_device.rs"]],["texture",[],["fallback_image.rs","hdr_texture_loader.rs","image.rs","image_texture_conversion.rs","image_texture_loader.rs","ktx2.rs","mod.rs","texture_cache.rs"]],["view",[["visibility",[],["mod.rs","render_layers.rs"]]],["mod.rs","window.rs"]]],["extract_component.rs","extract_param.rs","extract_resource.rs","globals.rs","lib.rs","pipelined_rendering.rs","render_asset.rs","settings.rs","spatial_bundle.rs"]],\
"bevy_render_macros":["",[],["as_bind_group.rs","extract_component.rs","extract_resource.rs","lib.rs"]],\
"bevy_scene":["",[],["bundle.rs","dynamic_scene.rs","dynamic_scene_builder.rs","lib.rs","scene.rs","scene_loader.rs","scene_spawner.rs","serde.rs"]],\
"bevy_sprite":["",[["mesh2d",[],["color_material.rs","material.rs","mesh.rs","mod.rs"]],["render",[],["mod.rs"]]],["bundle.rs","collide_aabb.rs","dynamic_texture_atlas_builder.rs","lib.rs","sprite.rs","texture_atlas.rs","texture_atlas_builder.rs"]],\
"bevy_tasks":["",[["iter",[],["adapters.rs","mod.rs"]]],["lib.rs","slice.rs","task.rs","task_pool.rs","thread_executor.rs","usages.rs"]],\
"bevy_text":["",[],["error.rs","font.rs","font_atlas.rs","font_atlas_set.rs","font_loader.rs","glyph_brush.rs","lib.rs","pipeline.rs","text.rs","text2d.rs"]],\
"bevy_time":["",[],["common_conditions.rs","fixed_timestep.rs","lib.rs","stopwatch.rs","time.rs","timer.rs"]],\
"bevy_transform":["",[["components",[],["global_transform.rs","mod.rs","transform.rs"]]],["commands.rs","lib.rs","systems.rs"]],\
"bevy_ui":["",[["flex",[],["convert.rs","mod.rs"]],["render",[],["mod.rs","pipeline.rs","render_pass.rs"]],["widget",[],["button.rs","image.rs","label.rs","mod.rs","text.rs"]]],["accessibility.rs","camera_config.rs","focus.rs","geometry.rs","lib.rs","node_bundles.rs","stack.rs","ui_node.rs","update.rs"]],\
"bevy_utils":["",[],["default.rs","float_ord.rs","futures.rs","label.rs","lib.rs","short_names.rs","synccell.rs","syncunsafecell.rs"]],\
"bevy_utils_proc_macros":["",[],["lib.rs"]],\
"bevy_window":["",[],["cursor.rs","event.rs","lib.rs","raw_handle.rs","system.rs","window.rs"]],\
"bevy_winit":["",[],["accessibility.rs","converters.rs","lib.rs","system.rs","winit_config.rs","winit_windows.rs"]],\
"bincode":["",[["de",[],["decoder.rs","impl_core.rs","impl_tuples.rs","impls.rs","mod.rs","read.rs"]],["enc",[],["encoder.rs","impl_tuples.rs","impls.rs","mod.rs","write.rs"]],["features",[],["derive.rs","impl_alloc.rs","impl_std.rs","mod.rs"]],["varint",[],["decode_signed.rs","decode_unsigned.rs","encode_signed.rs","encode_unsigned.rs","mod.rs"]]],["atomic.rs","config.rs","error.rs","lib.rs","utils.rs"]],\
"bincode_derive":["",[],["attribute.rs","derive_enum.rs","derive_struct.rs","lib.rs"]],\
"bit_set":["",[],["lib.rs"]],\
"bit_vec":["",[],["lib.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bitvec":["",[["array",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["boxed",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["field",[],["io.rs"]],["macros",[],["internal.rs"]],["ptr",[],["addr.rs","proxy.rs","range.rs","single.rs","span.rs"]],["slice",[["specialization",[],["lsb0.rs","msb0.rs"]]],["api.rs","iter.rs","ops.rs","specialization.rs","traits.rs"]],["vec",[],["api.rs","iter.rs","ops.rs","traits.rs"]]],["access.rs","array.rs","boxed.rs","devel.rs","domain.rs","field.rs","index.rs","lib.rs","macros.rs","mem.rs","order.rs","ptr.rs","slice.rs","store.rs","vec.rs","view.rs"]],\
"bytemuck":["",[],["allocation.rs","anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"bytemuck_derive":["",[],["lib.rs","traits.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"clap":["",[["builder",[],["action.rs","app_settings.rs","arg.rs","arg_group.rs","arg_predicate.rs","arg_settings.rs","command.rs","debug_asserts.rs","mod.rs","os_str.rs","possible_value.rs","range.rs","resettable.rs","str.rs","styled_str.rs","value_hint.rs","value_parser.rs"]],["error",[],["context.rs","format.rs","kind.rs","mod.rs"]],["output",[["textwrap",[],["core.rs","mod.rs"]]],["fmt.rs","help.rs","help_template.rs","mod.rs","usage.rs"]],["parser",[["features",[],["mod.rs","suggestions.rs"]],["matches",[],["any_value.rs","arg_matches.rs","matched_arg.rs","mod.rs","value_source.rs"]]],["arg_matcher.rs","error.rs","mod.rs","parser.rs","validator.rs"]],["util",[],["color.rs","flat_map.rs","flat_set.rs","graph.rs","id.rs","mod.rs","str_to_bool.rs"]]],["derive.rs","lib.rs","macros.rs","mkeymap.rs"]],\
"clap_derive":["",[["derives",[],["args.rs","into_app.rs","mod.rs","parser.rs","subcommand.rs","value_enum.rs"]],["utils",[],["doc_comments.rs","error.rs","mod.rs","spanned.rs","ty.rs"]]],["attr.rs","dummies.rs","item.rs","lib.rs","macros.rs"]],\
"clap_lex":["",[],["lib.rs"]],\
"codespan_reporting":["",[["term",[],["config.rs","renderer.rs","views.rs"]]],["diagnostic.rs","files.rs","lib.rs","term.rs"]],\
"color_quant":["",[],["lib.rs","math.rs"]],\
"concurrent_queue":["",[],["bounded.rs","lib.rs","single.rs","sync.rs","unbounded.rs"]],\
"const_panic":["",[["fmt",[],["char_formatting.rs"]],["fmt_impls",[],["basic_fmt_impls.rs"]],["macros",[],["concat_assert.rs","unwrapping.rs"]]],["concat_panic_.rs","debug_str_fmt.rs","doc_macros.rs","fmt.rs","int_formatting.rs","lib.rs","macros.rs","panic_val.rs","utils.rs","wrapper.rs"]],\
"cpal":["",[["host",[["alsa",[],["enumerate.rs","mod.rs"]],["null",[],["mod.rs"]]],["mod.rs"]],["platform",[],["mod.rs"]]],["error.rs","lib.rs","samples_formats.rs","traits.rs"]],\
"crc32fast":["",[["specialized",[],["mod.rs","pclmulqdq.rs"]]],["baseline.rs","combine.rs","lib.rs","table.rs"]],\
"crossbeam_channel":["",[["flavors",[],["array.rs","at.rs","list.rs","mod.rs","never.rs","tick.rs","zero.rs"]]],["channel.rs","context.rs","counter.rs","err.rs","lib.rs","select.rs","select_macro.rs","utils.rs","waker.rs"]],\
"crossbeam_utils":["",[["atomic",[],["atomic_cell.rs","consume.rs","mod.rs","seq_lock.rs"]],["sync",[],["mod.rs","once_lock.rs","parker.rs","sharded_lock.rs","wait_group.rs"]]],["backoff.rs","cache_padded.rs","lib.rs","thread.rs"]],\
"cty":["",[],["lib.rs"]],\
"dasp_sample":["",[],["conv.rs","lib.rs","ops.rs","types.rs"]],\
"delegate":["",[],["lib.rs"]],\
"derivative":["",[],["ast.rs","attr.rs","bound.rs","clone.rs","cmp.rs","debug.rs","default.rs","hash.rs","lib.rs","matcher.rs","paths.rs","utils.rs"]],\
"downcast_rs":["",[],["lib.rs"]],\
"ecolor":["",[],["color32.rs","hsva.rs","hsva_gamma.rs","lib.rs","rgba.rs"]],\
"egui":["",[["containers",[],["area.rs","collapsing_header.rs","combo_box.rs","frame.rs","mod.rs","panel.rs","popup.rs","resize.rs","scroll_area.rs","window.rs"]],["data",[],["input.rs","mod.rs","output.rs"]],["input_state",[],["touch_state.rs"]],["util",[],["cache.rs","fixed_cache.rs","id_type_map.rs","mod.rs","undoer.rs"]],["widgets",[["plot",[["items",[],["bar.rs","box_elem.rs","mod.rs","rect_elem.rs","values.rs"]]],["legend.rs","mod.rs","transform.rs"]],["text_edit",[],["builder.rs","cursor_range.rs","mod.rs","output.rs","state.rs","text_buffer.rs"]]],["button.rs","color_picker.rs","drag_value.rs","hyperlink.rs","image.rs","label.rs","mod.rs","progress_bar.rs","selected_label.rs","separator.rs","slider.rs","spinner.rs"]]],["animation_manager.rs","context.rs","frame_state.rs","grid.rs","gui_zoom.rs","id.rs","input_state.rs","introspection.rs","layers.rs","layout.rs","lib.rs","memory.rs","menu.rs","os.rs","painter.rs","placer.rs","response.rs","sense.rs","style.rs","ui.rs","widget_text.rs"]],\
"either":["",[],["lib.rs"]],\
"emath":["",[],["align.rs","history.rs","lib.rs","numeric.rs","pos2.rs","rect.rs","rect_transform.rs","rot2.rs","smart_aim.rs","vec2.rs"]],\
"encase":["",[["core",[],["alignment_value.rs","buffers.rs","mod.rs","rw.rs","size_value.rs","traits.rs"]],["impls",[],["glam.rs","mod.rs"]],["types",[],["array.rs","matrix.rs","mod.rs","runtime_sized_array.rs","scalar.rs","struct.rs","vector.rs","wrapper.rs"]]],["lib.rs","utils.rs"]],\
"encase_derive":["",[],["lib.rs"]],\
"encase_derive_impl":["",[],["lib.rs"]],\
"epaint":["",[["text",[],["cursor.rs","font.rs","fonts.rs","mod.rs","text_layout.rs","text_layout_types.rs"]],["util",[],["mod.rs","ordered_float.rs"]]],["bezier.rs","image.rs","lib.rs","mesh.rs","mutex.rs","shadow.rs","shape.rs","shape_transform.rs","stats.rs","stroke.rs","tessellator.rs","texture_atlas.rs","texture_handle.rs","textures.rs"]],\
"erased_serde":["",[["features_check",[],["mod.rs"]]],["any.rs","de.rs","error.rs","lib.rs","macros.rs","map.rs","private.rs","ser.rs"]],\
"euclid":["",[],["angle.rs","approxeq.rs","approxord.rs","box2d.rs","box3d.rs","homogen.rs","length.rs","lib.rs","macros.rs","num.rs","point.rs","rect.rs","rigid.rs","rotation.rs","scale.rs","side_offsets.rs","size.rs","transform2d.rs","transform3d.rs","translation.rs","trig.rs","vector.rs"]],\
"event_listener":["",[],["lib.rs"]],\
"fastrand":["",[],["lib.rs"]],\
"filetime":["",[["unix",[],["linux.rs","mod.rs","utimes.rs"]]],["lib.rs"]],\
"fixedbitset":["",[],["lib.rs","range.rs"]],\
"flate2":["",[["deflate",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["ffi",[],["mod.rs","rust.rs"]],["gz",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["zlib",[],["bufread.rs","mod.rs","read.rs","write.rs"]]],["bufreader.rs","crc.rs","lib.rs","mem.rs","zio.rs"]],\
"float_next_after":["",[],["lib.rs"]],\
"fnv":["",[],["lib.rs"]],\
"form_urlencoded":["",[],["lib.rs"]],\
"funty":["",[],["lib.rs"]],\
"futures_core":["",[["task",[["__internal",[],["atomic_waker.rs","mod.rs"]]],["mod.rs","poll.rs"]]],["future.rs","lib.rs","stream.rs"]],\
"futures_io":["",[],["lib.rs"]],\
"futures_lite":["",[],["future.rs","io.rs","lib.rs","prelude.rs","stream.rs"]],\
"fxhash":["",[],["lib.rs"]],\
"gethostname":["",[],["lib.rs"]],\
"getrandom":["",[],["error.rs","lib.rs","linux_android.rs","use_file.rs","util.rs","util_libc.rs"]],\
"gilrs":["",[["ev",[],["filter.rs","mod.rs","state.rs"]],["ff",[],["base_effect.rs","effect_source.rs","mod.rs","server.rs","time.rs"]],["mapping",[],["mod.rs","parser.rs"]]],["constants.rs","gamepad.rs","lib.rs","utils.rs"]],\
"gilrs_core":["",[["platform",[["linux",[],["ff.rs","gamepad.rs","ioctl.rs","mod.rs","udev.rs"]]],["mod.rs"]]],["lib.rs","utils.rs"]],\
"glam":["",[["bool",[["sse2",[],["bvec3a.rs","bvec4a.rs"]]],["bvec2.rs","bvec3.rs","bvec4.rs","sse2.rs"]],["f32",[["sse2",[],["mat2.rs","mat3a.rs","mat4.rs","quat.rs","vec3a.rs","vec4.rs"]]],["affine2.rs","affine3a.rs","mat3.rs","sse2.rs","vec2.rs","vec3.rs"]],["f64",[],["daffine2.rs","daffine3.rs","dmat2.rs","dmat3.rs","dmat4.rs","dquat.rs","dvec2.rs","dvec3.rs","dvec4.rs"]],["features",[],["impl_bytemuck.rs","impl_serde.rs"]],["i32",[],["ivec2.rs","ivec3.rs","ivec4.rs"]],["swizzles",[["sse2",[],["vec3a_impl.rs","vec4_impl.rs"]]],["dvec2_impl.rs","dvec3_impl.rs","dvec4_impl.rs","ivec2_impl.rs","ivec3_impl.rs","ivec4_impl.rs","sse2.rs","uvec2_impl.rs","uvec3_impl.rs","uvec4_impl.rs","vec2_impl.rs","vec3_impl.rs","vec_traits.rs"]],["u32",[],["uvec2.rs","uvec3.rs","uvec4.rs"]]],["align16.rs","bool.rs","deref.rs","euler.rs","f32.rs","f64.rs","features.rs","float_ex.rs","i32.rs","lib.rs","macros.rs","sse2.rs","swizzles.rs","u32.rs"]],\
"glow":["",[],["gl46.rs","lib.rs","native.rs","version.rs"]],\
"gltf":["",[["accessor",[],["mod.rs","sparse.rs","util.rs"]],["animation",[["util",[],["mod.rs","morph_target_weights.rs","rotations.rs"]]],["iter.rs","mod.rs"]],["mesh",[["util",[],["colors.rs","indices.rs","joints.rs","mod.rs","tex_coords.rs","weights.rs"]]],["iter.rs","mod.rs"]],["scene",[],["iter.rs","mod.rs"]],["skin",[],["iter.rs","mod.rs","util.rs"]]],["binary.rs","buffer.rs","camera.rs","image.rs","iter.rs","khr_lights_punctual.rs","lib.rs","material.rs","math.rs","texture.rs"]],\
"gltf_derive":["",[],["lib.rs"]],\
"gltf_json":["",[["extensions",[],["accessor.rs","animation.rs","asset.rs","buffer.rs","camera.rs","image.rs","material.rs","mesh.rs","mod.rs","root.rs","scene.rs","skin.rs","texture.rs"]]],["accessor.rs","animation.rs","asset.rs","buffer.rs","camera.rs","extras.rs","image.rs","lib.rs","material.rs","mesh.rs","path.rs","root.rs","scene.rs","skin.rs","texture.rs","validation.rs"]],\
"glyph_brush_layout":["",[],["builtin.rs","characters.rs","font.rs","lib.rs","linebreak.rs","lines.rs","section.rs","words.rs"]],\
"gpu_alloc":["",[],["allocator.rs","block.rs","buddy.rs","config.rs","error.rs","freelist.rs","heap.rs","lib.rs","slab.rs","usage.rs","util.rs"]],\
"gpu_alloc_types":["",[],["device.rs","lib.rs","types.rs"]],\
"gpu_descriptor":["",[],["allocator.rs","lib.rs"]],\
"gpu_descriptor_types":["",[],["device.rs","lib.rs","types.rs"]],\
"guillotiere":["",[],["allocator.rs","lib.rs"]],\
"hashbrown":["",[["external_trait_impls",[],["mod.rs","serde.rs"]],["raw",[],["alloc.rs","bitmask.rs","mod.rs","sse2.rs"]]],["lib.rs","macros.rs","map.rs","scopeguard.rs","set.rs"]],\
"heck":["",[],["kebab.rs","lib.rs","lower_camel.rs","shouty_kebab.rs","shouty_snake.rs","snake.rs","title.rs","upper_camel.rs"]],\
"hexasphere":["",[],["interpolation.rs","lib.rs","shapes.rs","slice.rs"]],\
"hexf_parse":["",[],["lib.rs"]],\
"idna":["",[],["lib.rs","punycode.rs","uts46.rs"]],\
"image":["",[["codecs",[["hdr",[],["decoder.rs","encoder.rs","mod.rs"]],["jpeg",[],["decoder.rs","encoder.rs","entropy.rs","mod.rs","transform.rs"]]],["png.rs"]],["imageops",[],["affine.rs","colorops.rs","mod.rs","sample.rs"]],["io",[],["free_functions.rs","mod.rs","reader.rs"]],["math",[],["mod.rs","rect.rs","utils.rs"]],["utils",[],["mod.rs"]]],["animation.rs","buffer.rs","color.rs","dynimage.rs","error.rs","flat.rs","image.rs","lib.rs","traits.rs"]],\
"indexmap":["",[["map",[["core",[],["raw.rs"]]],["core.rs"]]],["arbitrary.rs","equivalent.rs","lib.rs","macros.rs","map.rs","mutable_keys.rs","set.rs","util.rs"]],\
"inflections":["",[],["case.rs","lib.rs"]],\
"inotify":["",[],["events.rs","fd_guard.rs","inotify.rs","lib.rs","util.rs","watches.rs"]],\
"inotify_sys":["",[],["lib.rs"]],\
"instant":["",[],["lib.rs","native.rs"]],\
"io_lifetimes":["",[],["example_ffi.rs","lib.rs","portability.rs","raw.rs","traits.rs","views.rs"]],\
"is_terminal":["",[],["lib.rs"]],\
"itertools":["",[["adaptors",[],["coalesce.rs","map.rs","mod.rs","multi_product.rs"]]],["combinations.rs","combinations_with_replacement.rs","concat_impl.rs","cons_tuples_impl.rs","diff.rs","duplicates_impl.rs","either_or_both.rs","exactly_one_err.rs","extrema_set.rs","flatten_ok.rs","format.rs","free.rs","group_map.rs","groupbylazy.rs","grouping_map.rs","impl_macros.rs","intersperse.rs","k_smallest.rs","kmerge_impl.rs","lazy_buffer.rs","lib.rs","merge_join.rs","minmax.rs","multipeek_impl.rs","pad_tail.rs","peek_nth.rs","peeking_take_while.rs","permutations.rs","powerset.rs","process_results_impl.rs","put_back_n_impl.rs","rciter_impl.rs","repeatn.rs","size_hint.rs","sources.rs","tee.rs","tuple_impl.rs","unique_impl.rs","unziptuple.rs","with_position.rs","zip_eq_impl.rs","zip_longest.rs","ziptuple.rs"]],\
"itoa":["",[],["lib.rs","udiv128.rs"]],\
"jpeg_decoder":["",[["arch",[],["mod.rs","neon.rs","ssse3.rs"]],["decoder",[],["lossless.rs"]],["worker",[],["immediate.rs","mod.rs","multithreaded.rs"]]],["decoder.rs","error.rs","huffman.rs","idct.rs","lib.rs","marker.rs","parser.rs","upsampler.rs"]],\
"khronos_egl":["",[],["lib.rs"]],\
"ktx2":["",[],["enums.rs","error.rs","lib.rs"]],\
"lazy_static":["",[],["inline_lazy.rs","lib.rs"]],\
"lewton":["",[],["audio.rs","bitpacking.rs","header.rs","header_cached.rs","huffman_tree.rs","imdct.rs","inside_ogg.rs","lib.rs","samples.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"libloading":["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]],\
"libm":["",[["math",[],["acos.rs","acosf.rs","acosh.rs","acoshf.rs","asin.rs","asinf.rs","asinh.rs","asinhf.rs","atan.rs","atan2.rs","atan2f.rs","atanf.rs","atanh.rs","atanhf.rs","cbrt.rs","cbrtf.rs","ceil.rs","ceilf.rs","copysign.rs","copysignf.rs","cos.rs","cosf.rs","cosh.rs","coshf.rs","erf.rs","erff.rs","exp.rs","exp10.rs","exp10f.rs","exp2.rs","exp2f.rs","expf.rs","expm1.rs","expm1f.rs","expo2.rs","fabs.rs","fabsf.rs","fdim.rs","fdimf.rs","fenv.rs","floor.rs","floorf.rs","fma.rs","fmaf.rs","fmax.rs","fmaxf.rs","fmin.rs","fminf.rs","fmod.rs","fmodf.rs","frexp.rs","frexpf.rs","hypot.rs","hypotf.rs","ilogb.rs","ilogbf.rs","j0.rs","j0f.rs","j1.rs","j1f.rs","jn.rs","jnf.rs","k_cos.rs","k_cosf.rs","k_expo2.rs","k_expo2f.rs","k_sin.rs","k_sinf.rs","k_tan.rs","k_tanf.rs","ldexp.rs","ldexpf.rs","lgamma.rs","lgamma_r.rs","lgammaf.rs","lgammaf_r.rs","log.rs","log10.rs","log10f.rs","log1p.rs","log1pf.rs","log2.rs","log2f.rs","logf.rs","mod.rs","modf.rs","modff.rs","nextafter.rs","nextafterf.rs","pow.rs","powf.rs","rem_pio2.rs","rem_pio2_large.rs","rem_pio2f.rs","remainder.rs","remainderf.rs","remquo.rs","remquof.rs","rint.rs","rintf.rs","round.rs","roundf.rs","scalbn.rs","scalbnf.rs","sin.rs","sincos.rs","sincosf.rs","sinf.rs","sinh.rs","sinhf.rs","sqrt.rs","sqrtf.rs","tan.rs","tanf.rs","tanh.rs","tanhf.rs","tgamma.rs","tgammaf.rs","trunc.rs","truncf.rs"]]],["lib.rs"]],\
"libre_pvz":["",[["core",[],["behaviour.rs","geometry.rs","kinematics.rs","projectile.rs"]],["plant",[],["peashooter.rs"]],["scene",[],["almanac.rs","lawn.rs","loading.rs"]]],["core.rs","diagnostics.rs","lib.rs","plant.rs","scene.rs","seed_bank.rs"]],\
"libre_pvz_animation":["",[["curve",[],["animatable.rs","blend.rs","builder.rs","concrete.rs"]]],["clip.rs","curve.rs","lib.rs","player.rs","transform.rs"]],\
"libre_pvz_resources":["",[],["animation.rs","cached.rs","dynamic.rs","lib.rs","loader.rs","model.rs"]],\
"libudev_sys":["",[],["lib.rs"]],\
"linux_raw_sys":["",[["x86_64",[],["errno.rs","general.rs","ioctl.rs"]]],["lib.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"lyon_algorithms":["",[],["aabb.rs","area.rs","fit.rs","hatching.rs","hit_test.rs","length.rs","lib.rs","measure.rs","raycast.rs","rect.rs","rounded_polygon.rs","walk.rs","winding.rs"]],\
"lyon_geom":["",[],["arc.rs","cubic_bezier.rs","cubic_bezier_intersections.rs","lib.rs","line.rs","quadratic_bezier.rs","segment.rs","triangle.rs","utils.rs"]],\
"lyon_path":["",[],["builder.rs","commands.rs","events.rs","iterator.rs","lib.rs","path.rs","path_buffer.rs","polygon.rs","private.rs"]],\
"lyon_tessellation":["",[],["basic_shapes.rs","event_queue.rs","fill.rs","geometry_builder.rs","lib.rs","math_utils.rs","monotone.rs","stroke.rs"]],\
"matchers":["",[],["lib.rs"]],\
"matches":["",[],["lib.rs"]],\
"memchr":["",[["memchr",[["x86",[],["avx.rs","mod.rs","sse2.rs"]]],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[["x86",[],["avx.rs","mod.rs","sse.rs"]]],["fallback.rs","genericsimd.rs","mod.rs"]],["x86",[],["avx.rs","mod.rs","sse.rs"]]],["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]]],["cow.rs","lib.rs"]],\
"miniz_oxide":["",[["deflate",[],["buffer.rs","core.rs","mod.rs","stream.rs"]],["inflate",[],["core.rs","mod.rs","output_buffer.rs","stream.rs"]]],["lib.rs","shared.rs"]],\
"mio":["",[["event",[],["event.rs","events.rs","mod.rs","source.rs"]],["sys",[["unix",[["selector",[],["epoll.rs","mod.rs"]]],["mod.rs","pipe.rs","sourcefd.rs","waker.rs"]]],["mod.rs"]]],["interest.rs","io_source.rs","lib.rs","macros.rs","poll.rs","token.rs","waker.rs"]],\
"naga":["",[["back",[["glsl",[],["features.rs","keywords.rs","mod.rs"]],["spv",[],["block.rs","helpers.rs","image.rs","index.rs","instructions.rs","layout.rs","mod.rs","recyclable.rs","selection.rs","writer.rs"]],["wgsl",[],["mod.rs","writer.rs"]]],["mod.rs"]],["front",[["glsl",[["parser",[],["declarations.rs","expressions.rs","functions.rs","types.rs"]]],["ast.rs","builtins.rs","constants.rs","context.rs","error.rs","functions.rs","lex.rs","mod.rs","offset.rs","parser.rs","token.rs","types.rs","variables.rs"]],["spv",[],["convert.rs","error.rs","function.rs","image.rs","mod.rs","null.rs"]],["wgsl",[],["ast.rs","construction.rs","conv.rs","index.rs","lexer.rs","mod.rs","number.rs"]]],["interpolator.rs","mod.rs"]],["keywords",[],["mod.rs","wgsl.rs"]],["proc",[],["index.rs","layouter.rs","mod.rs","namer.rs","terminator.rs","typifier.rs"]],["valid",[],["analyzer.rs","compose.rs","expression.rs","function.rs","handles.rs","interface.rs","mod.rs","type.rs"]]],["arena.rs","block.rs","lib.rs","span.rs"]],\
"nix":["",[["sys",[["ioctl",[],["linux.rs","mod.rs"]]],["mod.rs","signal.rs","sysinfo.rs","time.rs"]]],["errno.rs","fcntl.rs","lib.rs","macros.rs","unistd.rs"]],\
"nohash_hasher":["",[],["lib.rs"]],\
"notify":["",[],["config.rs","error.rs","event.rs","inotify.rs","lib.rs","null.rs","poll.rs"]],\
"nu_ansi_term":["",[],["ansi.rs","debug.rs","difference.rs","display.rs","gradient.rs","lib.rs","rgb.rs","style.rs","util.rs","windows.rs","write.rs"]],\
"num_integer":["",[],["average.rs","lib.rs","roots.rs"]],\
"num_rational":["",[],["lib.rs","pow.rs"]],\
"num_traits":["",[["ops",[],["checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"ogg":["",[],["crc.rs","lib.rs","reading.rs","writing.rs"]],\
"once_cell":["",[],["imp_pl.rs","lib.rs","race.rs"]],\
"optics":["",[],["concrete.rs","lib.rs","prelude.rs","traits.rs"]],\
"os_str_bytes":["",[["common",[],["mod.rs","raw.rs"]]],["iter.rs","lib.rs","pattern.rs","raw_str.rs"]],\
"overload":["",[],["assignment.rs","binary.rs","lib.rs","unary.rs"]],\
"owned_ttf_parser":["",[],["convert.rs","lib.rs","owned.rs","preparse.rs"]],\
"parking":["",[],["lib.rs"]],\
"parking_lot":["",[],["condvar.rs","deadlock.rs","elision.rs","fair_mutex.rs","lib.rs","mutex.rs","once.rs","raw_fair_mutex.rs","raw_mutex.rs","raw_rwlock.rs","remutex.rs","rwlock.rs","util.rs"]],\
"parking_lot_core":["",[["thread_parker",[],["linux.rs","mod.rs"]]],["lib.rs","parking_lot.rs","spinwait.rs","util.rs","word_lock.rs"]],\
"percent_encoding":["",[],["lib.rs"]],\
"petgraph":["",[["algo",[],["astar.rs","bellman_ford.rs","dijkstra.rs","dominators.rs","feedback_arc_set.rs","floyd_warshall.rs","isomorphism.rs","k_shortest_path.rs","matching.rs","mod.rs","simple_paths.rs","tred.rs"]],["graph_impl",[["stable_graph",[],["mod.rs"]]],["frozen.rs","mod.rs"]],["visit",[],["dfsvisit.rs","filter.rs","macros.rs","mod.rs","reversed.rs","traversal.rs"]]],["adj.rs","csr.rs","data.rs","dot.rs","graphmap.rs","iter_format.rs","iter_utils.rs","lib.rs","macros.rs","matrix_graph.rs","operator.rs","prelude.rs","scored.rs","traits_graph.rs","unionfind.rs","util.rs"]],\
"pin_project_lite":["",[],["lib.rs"]],\
"png":["",[["decoder",[],["mod.rs","stream.rs","zlib.rs"]]],["chunk.rs","common.rs","encoder.rs","filter.rs","lib.rs","srgb.rs","text_metadata.rs","traits.rs","utils.rs"]],\
"pp_rs":["",[["pp",[],["if_parser.rs"]]],["lexer.rs","lib.rs","pp.rs","token.rs"]],\
"pretty_type_name":["",[],["lib.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"profiling":["",[],["empty_impl.rs","lib.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"radium":["",[],["lib.rs","macros.rs","types.rs"]],\
"radsort":["",[],["lib.rs","scalar.rs","sort.rs"]],\
"raw_window_handle":["",[],["android.rs","appkit.rs","haiku.rs","lib.rs","redox.rs","uikit.rs","unix.rs","web.rs","windows.rs"]],\
"reanim_decode":["",[],["cli.rs","lib.rs","reanim.rs","stream.rs","xml.rs"]],\
"rectangle_pack":["",[["bin_section",[],["overlaps.rs"]],["target_bin",[],["coalesce.rs","push_available_bin_section.rs"]]],["bin_section.rs","box_size_heuristics.rs","grouped_rects_to_place.rs","lib.rs","packed_location.rs","rect_to_insert.rs","target_bin.rs","width_height_depth.rs"]],\
"regex":["",[["literal",[],["imp.rs","mod.rs"]]],["backtrack.rs","compile.rs","dfa.rs","error.rs","exec.rs","expand.rs","find_byte.rs","input.rs","lib.rs","pikevm.rs","pool.rs","prog.rs","re_builder.rs","re_bytes.rs","re_set.rs","re_trait.rs","re_unicode.rs","sparse.rs","utf8.rs"]],\
"regex_automata":["",[["nfa",[],["compiler.rs","map.rs","mod.rs","range_trie.rs"]]],["byteorder.rs","classes.rs","dense.rs","determinize.rs","dfa.rs","error.rs","lib.rs","minimize.rs","regex.rs","sparse.rs","sparse_set.rs","state_id.rs"]],\
"regex_syntax":["",[["ast",[],["mod.rs","parse.rs","print.rs","visitor.rs"]],["hir",[["literal",[],["mod.rs"]]],["interval.rs","mod.rs","print.rs","translate.rs","visitor.rs"]],["unicode_tables",[],["age.rs","case_folding_simple.rs","general_category.rs","grapheme_cluster_break.rs","mod.rs","perl_word.rs","property_bool.rs","property_names.rs","property_values.rs","script.rs","script_extension.rs","sentence_break.rs","word_break.rs"]]],["either.rs","error.rs","lib.rs","parser.rs","unicode.rs","utf8.rs"]],\
"renderdoc_sys":["",[],["bindings.rs","lib.rs"]],\
"rodio":["",[["conversions",[],["channels.rs","mod.rs","sample.rs","sample_rate.rs"]],["decoder",[],["mod.rs","vorbis.rs"]],["source",[],["amplify.rs","blt.rs","buffered.rs","channel_volume.rs","crossfade.rs","delay.rs","done.rs","empty.rs","fadein.rs","from_factory.rs","from_iter.rs","mix.rs","mod.rs","pausable.rs","periodic.rs","repeat.rs","samples_converter.rs","sine.rs","skip.rs","skippable.rs","spatial.rs","speed.rs","stoppable.rs","take.rs","uniform.rs","zero.rs"]]],["buffer.rs","dynamic_mixer.rs","lib.rs","queue.rs","sink.rs","spatial_sink.rs","static_buffer.rs","stream.rs"]],\
"ron":["",[["de",[],["id.rs","mod.rs","tag.rs","value.rs"]],["ser",[],["mod.rs","value.rs"]]],["error.rs","extensions.rs","lib.rs","options.rs","parse.rs","value.rs"]],\
"rustc_hash":["",[],["lib.rs"]],\
"rustix":["",[["backend",[["linux_raw",[["arch",[["inline",[],["mod.rs","x86_64.rs"]]],["mod.rs"]],["io",[],["epoll.rs","errno.rs","mod.rs","poll_fd.rs","syscalls.rs","types.rs"]],["process",[],["cpu_set.rs","mod.rs","syscalls.rs","types.rs","wait.rs"]],["termios",[],["mod.rs","syscalls.rs","types.rs"]],["time",[],["mod.rs","types.rs"]]],["c.rs","conv.rs","elf.rs","mod.rs","reg.rs"]]]],["ffi",[],["mod.rs"]],["io",[],["close.rs","context.rs","dup.rs","errno.rs","eventfd.rs","fcntl.rs","ioctl.rs","is_read_write.rs","mod.rs","pipe.rs","poll.rs","read_write.rs","stdio.rs"]],["path",[],["arg.rs","mod.rs"]],["process",[],["chdir.rs","exit.rs","id.rs","kill.rs","membarrier.rs","mod.rs","prctl.rs","priority.rs","rlimit.rs","sched.rs","sched_yield.rs","uname.rs","wait.rs"]],["termios",[],["cf.rs","constants.rs","mod.rs","tc.rs","tty.rs"]]],["const_assert.rs","cstr.rs","lib.rs","utils.rs"]],\
"ruzstd":["",[["blocks",[],["block.rs","literals_section.rs","mod.rs","sequence_section.rs"]],["decoding",[],["bit_reader.rs","bit_reader_reverse.rs","block_decoder.rs","decodebuffer.rs","dictionary.rs","literals_section_decoder.rs","mod.rs","scratch.rs","sequence_execution.rs","sequence_section_decoder.rs"]],["errors",[],["mod.rs"]],["fse",[],["fse_decoder.rs","mod.rs"]],["huff0",[],["huff0_decoder.rs","mod.rs"]],["tests",[],["bit_reader.rs","decode_corpus.rs","dict_test.rs","fuzz_regressions.rs","mod.rs"]]],["frame.rs","frame_decoder.rs","lib.rs","streaming_decoder.rs"]],\
"ryu":["",[["buffer",[],["mod.rs"]],["pretty",[],["exponent.rs","mantissa.rs","mod.rs"]]],["common.rs","d2s.rs","d2s_full_table.rs","d2s_intrinsics.rs","digit_table.rs","f2s.rs","f2s_intrinsics.rs","lib.rs"]],\
"same_file":["",[],["lib.rs","unix.rs"]],\
"scoped_threadpool":["",[],["lib.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"serde":["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]],\
"serde_derive":["",[["internals",[],["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]]],["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","this.rs","try.rs"]],\
"serde_json":["",[["features_check",[],["mod.rs"]],["io",[],["mod.rs"]],["value",[],["de.rs","from.rs","index.rs","mod.rs","partial_eq.rs","ser.rs"]]],["de.rs","error.rs","iter.rs","lib.rs","macros.rs","map.rs","number.rs","raw.rs","read.rs","ser.rs"]],\
"serde_yaml":["",[["libyaml",[],["cstr.rs","emitter.rs","error.rs","mod.rs","parser.rs","tag.rs","util.rs"]],["value",[],["de.rs","debug.rs","from.rs","index.rs","mod.rs","partial_eq.rs","ser.rs","tagged.rs"]]],["de.rs","error.rs","lib.rs","loader.rs","mapping.rs","number.rs","path.rs","ser.rs","with.rs"]],\
"sharded_slab":["",[["page",[],["mod.rs","slot.rs","stack.rs"]]],["cfg.rs","clear.rs","implementation.rs","iter.rs","lib.rs","macros.rs","pool.rs","shard.rs","sync.rs","tid.rs"]],\
"siphasher":["",[],["lib.rs","sip.rs","sip128.rs"]],\
"slab":["",[],["lib.rs"]],\
"slotmap":["",[],["basic.rs","dense.rs","hop.rs","lib.rs","secondary.rs","sparse_secondary.rs"]],\
"smallvec":["",[],["lib.rs"]],\
"spirv":["",[],["autogen_spirv.rs","lib.rs"]],\
"static_assertions":["",[],["assert_cfg.rs","assert_eq_align.rs","assert_eq_size.rs","assert_fields.rs","assert_impl.rs","assert_obj_safe.rs","assert_trait.rs","assert_type.rs","const_assert.rs","lib.rs"]],\
"strsim":["",[],["lib.rs"]],\
"svg_fmt":["",[],["layout.rs","lib.rs","svg.rs"]],\
"svgtypes":["",[],["angle.rs","aspect_ratio.rs","color.rs","colors.rs","enable_background.rs","error.rs","filter_functions.rs","funciri.rs","length.rs","lib.rs","number.rs","paint.rs","paint_order.rs","path.rs","points.rs","stream.rs","transform.rs","viewbox.rs"]],\
"sysinfo":["",[["linux",[],["component.rs","cpu.rs","disk.rs","mod.rs","network.rs","process.rs","system.rs","utils.rs"]]],["common.rs","debug.rs","lib.rs","macros.rs","network.rs","network_helper_nix.rs","system.rs","traits.rs","users.rs","utils.rs"]],\
"taffy":["",[["compute",[["common",[],["alignment.rs","mod.rs"]]],["flexbox.rs","leaf.rs","mod.rs"]],["style",[],["alignment.rs","dimension.rs","flex.rs","mod.rs"]]],["axis.rs","data.rs","debug.rs","error.rs","geometry.rs","layout.rs","lib.rs","math.rs","node.rs","prelude.rs","resolve.rs","style_helpers.rs","sys.rs","tree.rs"]],\
"tap":["",[],["conv.rs","lib.rs","pipe.rs","tap.rs"]],\
"termcolor":["",[],["lib.rs"]],\
"thiserror":["",[],["aserror.rs","display.rs","lib.rs"]],\
"thiserror_impl":["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]],\
"thread_local":["",[],["cached.rs","lib.rs","thread_id.rs","unreachable.rs"]],\
"tinyvec":["",[["array",[],["generated_impl.rs"]]],["array.rs","arrayvec.rs","arrayvec_drain.rs","lib.rs","slicevec.rs","tinyvec.rs"]],\
"tinyvec_macros":["",[],["lib.rs"]],\
"toml_datetime":["",[],["datetime.rs","lib.rs"]],\
"toml_edit":["",[["parser",[],["array.rs","datetime.rs","document.rs","errors.rs","inline_table.rs","key.rs","macros.rs","mod.rs","numbers.rs","state.rs","strings.rs","table.rs","trivia.rs","value.rs"]]],["array.rs","array_of_tables.rs","document.rs","encode.rs","index.rs","inline_table.rs","internal_string.rs","item.rs","key.rs","lib.rs","raw_string.rs","repr.rs","table.rs","value.rs","visit.rs","visit_mut.rs"]],\
"tracing":["",[],["dispatcher.rs","field.rs","instrument.rs","level_filters.rs","lib.rs","macros.rs","span.rs","stdlib.rs","subscriber.rs"]],\
"tracing_attributes":["",[],["attr.rs","expand.rs","lib.rs"]],\
"tracing_core":["",[],["callsite.rs","dispatcher.rs","event.rs","field.rs","lazy.rs","lib.rs","metadata.rs","parent.rs","span.rs","stdlib.rs","subscriber.rs"]],\
"tracing_log":["",[],["lib.rs","log_tracer.rs","trace_logger.rs"]],\
"tracing_subscriber":["",[["field",[],["debug.rs","delimited.rs","display.rs","mod.rs"]],["filter",[["env",[],["builder.rs","directive.rs","field.rs","mod.rs"]],["layer_filters",[],["combinator.rs","mod.rs"]]],["directive.rs","filter_fn.rs","level.rs","mod.rs","targets.rs"]],["fmt",[["format",[],["mod.rs","pretty.rs"]],["time",[],["datetime.rs","mod.rs"]]],["fmt_layer.rs","mod.rs","writer.rs"]],["layer",[],["context.rs","layered.rs","mod.rs"]],["registry",[],["extensions.rs","mod.rs","sharded.rs","stack.rs"]]],["lib.rs","macros.rs","prelude.rs","reload.rs","sync.rs","util.rs"]],\
"ttf_parser":["",[["ggg",[],["chained_context.rs","context.rs","feature_variations.rs","layout_table.rs","lookup.rs","mod.rs"]],["tables",[["cff",[],["argstack.rs","cff1.rs","cff2.rs","charset.rs","charstring.rs","dict.rs","encoding.rs","index.rs","mod.rs","std_names.rs"]],["cmap",[],["format0.rs","format10.rs","format12.rs","format13.rs","format14.rs","format2.rs","format4.rs","format6.rs","mod.rs"]]],["ankr.rs","avar.rs","cbdt.rs","cblc.rs","feat.rs","fvar.rs","gdef.rs","glyf.rs","gpos.rs","gsub.rs","gvar.rs","head.rs","hhea.rs","hmtx.rs","hvar.rs","kern.rs","kerx.rs","loca.rs","math.rs","maxp.rs","mod.rs","morx.rs","mvar.rs","name.rs","os2.rs","post.rs","sbix.rs","svg.rs","trak.rs","vhea.rs","vorg.rs"]]],["aat.rs","language.rs","lib.rs","parser.rs","var_store.rs"]],\
"twox_hash":["",[],["lib.rs","sixty_four.rs","thirty_two.rs","xxh3.rs"]],\
"unicode_bidi":["",[["char_data",[],["mod.rs","tables.rs"]]],["data_source.rs","deprecated.rs","explicit.rs","format_chars.rs","implicit.rs","level.rs","lib.rs","prepare.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"unicode_normalization":["",[],["__test_api.rs","decompose.rs","lib.rs","lookups.rs","no_std_prelude.rs","normalize.rs","perfect_hash.rs","quick_check.rs","recompose.rs","replace.rs","stream_safe.rs","tables.rs"]],\
"unicode_width":["",[],["lib.rs","tables.rs"]],\
"unicode_xid":["",[],["lib.rs","tables.rs"]],\
"unsafe_libyaml":["",[],["api.rs","dumper.rs","emitter.rs","lib.rs","loader.rs","macros.rs","parser.rs","reader.rs","scanner.rs","success.rs","writer.rs","yaml.rs"]],\
"url":["",[],["host.rs","lib.rs","origin.rs","parser.rs","path_segments.rs","quirks.rs","slicing.rs"]],\
"uuid":["",[["external",[],["serde_support.rs"]]],["builder.rs","error.rs","external.rs","fmt.rs","lib.rs","macros.rs","parser.rs","rng.rs","timestamp.rs","v4.rs"]],\
"vec_map":["",[],["lib.rs"]],\
"virtue":["",[["generate",[],["gen_struct.rs","generate_fn.rs","generate_mod.rs","generator.rs","impl.rs","impl_for.rs","mod.rs","stream_builder.rs"]],["parse",[],["attributes.rs","body.rs","data_type.rs","generics.rs","mod.rs","utils.rs","visibility.rs"]]],["error.rs","lib.rs","utils.rs"]],\
"waker_fn":["",[],["lib.rs"]],\
"walkdir":["",[],["dent.rs","error.rs","lib.rs","util.rs"]],\
"webbrowser":["",[],["lib.rs","unix.rs"]],\
"wgpu":["",[["backend",[],["direct.rs","mod.rs"]],["util",[],["belt.rs","device.rs","encoder.rs","indirect.rs","init.rs","mod.rs"]]],["context.rs","lib.rs","macros.rs"]],\
"wgpu_core":["",[["command",[],["bind.rs","bundle.rs","clear.rs","compute.rs","draw.rs","memory_init.rs","mod.rs","query.rs","render.rs","transfer.rs"]],["device",[],["life.rs","mod.rs","queue.rs"]],["init_tracker",[],["buffer.rs","mod.rs","texture.rs"]],["track",[],["buffer.rs","metadata.rs","mod.rs","range.rs","stateless.rs","texture.rs"]]],["binding_model.rs","conv.rs","error.rs","hub.rs","id.rs","instance.rs","lib.rs","pipeline.rs","present.rs","resource.rs","validation.rs"]],\
"wgpu_hal":["",[["auxil",[],["mod.rs","renderdoc.rs"]],["gles",[],["adapter.rs","command.rs","conv.rs","device.rs","egl.rs","mod.rs","queue.rs"]],["vulkan",[],["adapter.rs","command.rs","conv.rs","device.rs","instance.rs","mod.rs"]]],["empty.rs","lib.rs"]],\
"wgpu_types":["",[],["assertions.rs","lib.rs"]],\
"winit":["",[["platform",[],["mod.rs","run_return.rs","x11.rs"]],["platform_impl",[["linux",[["x11",[["ime",[],["callbacks.rs","context.rs","inner.rs","input_method.rs","mod.rs"]],["util",[],["atom.rs","client_msg.rs","cursor.rs","format.rs","geometry.rs","hint.rs","icon.rs","input.rs","keys.rs","memory.rs","mod.rs","modifiers.rs","randr.rs","window_property.rs","wm.rs"]]],["dnd.rs","event_processor.rs","events.rs","ffi.rs","mod.rs","monitor.rs","window.rs","xdisplay.rs"]]],["mod.rs"]]],["mod.rs"]]],["dpi.rs","error.rs","event.rs","event_loop.rs","icon.rs","lib.rs","monitor.rs","window.rs"]],\
"winnow":["",[["bits",[],["complete.rs","mod.rs","streaming.rs"]],["branch",[],["mod.rs"]],["bytes",[],["complete.rs","mod.rs","streaming.rs"]],["character",[],["complete.rs","mod.rs","streaming.rs"]],["combinator",[],["mod.rs"]],["multi",[],["mod.rs"]],["number",[],["complete.rs","mod.rs","streaming.rs"]],["sequence",[],["mod.rs"]],["stream",[],["impls.rs","mod.rs"]],["trace",[],["mod.rs"]]],["error.rs","lib.rs","macros.rs","parser.rs"]],\
"wyz":["",[],["bidi.rs","comu.rs","fmt.rs","lib.rs","range.rs"]],\
"x11_dl":["",[],["dpms.rs","error.rs","glx.rs","internal.rs","keysym.rs","lib.rs","link.rs","old_xrandr.rs","sync.rs","xcursor.rs","xf86vmode.rs","xfixes.rs","xft.rs","xinerama.rs","xinput.rs","xinput2.rs","xlib.rs","xlib_xcb.rs","xmd.rs","xmu.rs","xpresent.rs","xrandr.rs","xrecord.rs","xrender.rs","xshm.rs","xss.rs","xt.rs","xtest.rs"]],\
"x11rb":["",[["protocol",[],["bigreq.rs","ge.rs","mod.rs","xc_misc.rs","xproto.rs"]],["rust_connection",[],["mod.rs","packet_reader.rs","stream.rs","write_buffer.rs"]]],["connection.rs","cookie.rs","errors.rs","event_loop_integration.rs","extension_manager.rs","lib.rs","properties.rs","utils.rs","wrapper.rs","x11_utils.rs"]],\
"x11rb_protocol":["",[["connection",[],["mod.rs"]],["parse_display",[],["connect_instruction.rs","mod.rs"]],["protocol",[],["bigreq.rs","ge.rs","mod.rs","xc_misc.rs","xproto.rs"]]],["connect.rs","errors.rs","id_allocator.rs","lib.rs","packet_reader.rs","utils.rs","wrapper.rs","x11_utils.rs","xauth.rs"]],\
"xi_unicode":["",[],["lib.rs","tables.rs"]]\
}');
createSourceSidebar();
