(function() {var implementors = {
"bevy":[],
"bevy_animation":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_animation/struct.AnimationClip.html\" title=\"struct bevy_animation::AnimationClip\">AnimationClip</a>"]],
"bevy_asset":[],
"bevy_audio":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_audio/struct.AudioSource.html\" title=\"struct bevy_audio::AudioSource\">AudioSource</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_audio/struct.Pitch.html\" title=\"struct bevy_audio::Pitch\">Pitch</a>"]],
"bevy_core_pipeline":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_core_pipeline/auto_exposure/struct.AutoExposureCompensationCurve.html\" title=\"struct bevy_core_pipeline::auto_exposure::AutoExposureCompensationCurve\">AutoExposureCompensationCurve</a>"]],
"bevy_gltf":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_gltf/struct.Gltf.html\" title=\"struct bevy_gltf::Gltf\">Gltf</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_gltf/struct.GltfMesh.html\" title=\"struct bevy_gltf::GltfMesh\">GltfMesh</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_gltf/struct.GltfNode.html\" title=\"struct bevy_gltf::GltfNode\">GltfNode</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_gltf/struct.GltfPrimitive.html\" title=\"struct bevy_gltf::GltfPrimitive\">GltfPrimitive</a>"]],
"bevy_pbr":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_pbr/struct.StandardMaterial.html\" title=\"struct bevy_pbr::StandardMaterial\">StandardMaterial</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_pbr/wireframe/struct.WireframeMaterial.html\" title=\"struct bevy_pbr::wireframe::WireframeMaterial\">WireframeMaterial</a>"],["impl&lt;B: <a class=\"trait\" href=\"bevy_pbr/trait.Material.html\" title=\"trait bevy_pbr::Material\">Material</a>, E: <a class=\"trait\" href=\"bevy_pbr/trait.MaterialExtension.html\" title=\"trait bevy_pbr::MaterialExtension\">MaterialExtension</a>&gt; <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_pbr/struct.ExtendedMaterial.html\" title=\"struct bevy_pbr::ExtendedMaterial\">ExtendedMaterial</a>&lt;B, E&gt;"]],
"bevy_render":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/mesh/skinning/struct.SkinnedMeshInverseBindposes.html\" title=\"struct bevy_render::mesh::skinning::SkinnedMeshInverseBindposes\">SkinnedMeshInverseBindposes</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/mesh/struct.Mesh.html\" title=\"struct bevy_render::mesh::Mesh\">Mesh</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/render_resource/struct.Shader.html\" title=\"struct bevy_render::render_resource::Shader\">Shader</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/texture/struct.Image.html\" title=\"struct bevy_render::texture::Image\">Image</a>"]],
"bevy_scene":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_scene/struct.DynamicScene.html\" title=\"struct bevy_scene::DynamicScene\">DynamicScene</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_scene/struct.Scene.html\" title=\"struct bevy_scene::Scene\">Scene</a>"]],
"bevy_sprite":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_sprite/struct.ColorMaterial.html\" title=\"struct bevy_sprite::ColorMaterial\">ColorMaterial</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_sprite/struct.TextureAtlasLayout.html\" title=\"struct bevy_sprite::TextureAtlasLayout\">TextureAtlasLayout</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_sprite/struct.Wireframe2dMaterial.html\" title=\"struct bevy_sprite::Wireframe2dMaterial\">Wireframe2dMaterial</a>"]],
"bevy_text":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_text/struct.Font.html\" title=\"struct bevy_text::Font\">Font</a>"]],
"libre_pvz_animation":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"libre_pvz_animation/clip/struct.AnimationClip.html\" title=\"struct libre_pvz_animation::clip::AnimationClip\">AnimationClip</a>"]],
"libre_pvz_resources":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"libre_pvz_resources/animation/struct.Animation.html\" title=\"struct libre_pvz_resources::animation::Animation\">Animation</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"libre_pvz_resources/model/struct.Model.html\" title=\"struct libre_pvz_resources::model::Model\">Model</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()