(function() {var implementors = {
"async_fs":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"async_fs/struct.File.html\" title=\"struct async_fs::File\">File</a>"]],
"calloop":[["impl&lt;'l, Data&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"calloop/struct.EventLoop.html\" title=\"struct calloop::EventLoop\">EventLoop</a>&lt;'l, Data&gt;"],["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"calloop/generic/struct.NoIoDrop.html\" title=\"struct calloop::generic::NoIoDrop\">NoIoDrop</a>&lt;T&gt;"],["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"calloop/generic/struct.FdWrapper.html\" title=\"struct calloop::generic::FdWrapper\">FdWrapper</a>&lt;T&gt;"]],
"inotify":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"inotify/struct.Inotify.html\" title=\"struct inotify::Inotify\">Inotify</a>"]],
"nix":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"nix/sys/eventfd/struct.EventFd.html\" title=\"struct nix::sys::eventfd::EventFd\">EventFd</a>"]],
"polling":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"polling/struct.Poller.html\" title=\"struct polling::Poller\">Poller</a>"]],
"rustix":[["impl&lt;'fd&gt; <a class=\"trait\" href=\"rustix/fd/trait.AsFd.html\" title=\"trait rustix::fd::AsFd\">AsFd</a> for <a class=\"struct\" href=\"rustix/event/struct.PollFd.html\" title=\"struct rustix::event::PollFd\">PollFd</a>&lt;'fd&gt;"]],
"winit":[["impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"winit/event_loop/struct.EventLoop.html\" title=\"struct winit::event_loop::EventLoop\">EventLoop</a>&lt;T&gt;"]],
"x11rb":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"x11rb/rust_connection/struct.DefaultStream.html\" title=\"struct x11rb::rust_connection::DefaultStream\">DefaultStream</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/std/os/fd/owned/trait.AsFd.html\" title=\"trait std::os::fd::owned::AsFd\">AsFd</a> for <a class=\"struct\" href=\"x11rb/xcb_ffi/struct.XCBConnection.html\" title=\"struct x11rb::xcb_ffi::XCBConnection\">XCBConnection</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()