/*
 * librePvZ: game logic implementation.
 * Copyright (c) 2023  Ruifeng Xie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Seed bank and seed packets.

use bevy::prelude::*;
use bevy::asset::Handle;
use bevy::sprite::TextureAtlas;
use bevy_asset_loader::prelude::*;
use crate::scene::loading::AssetState;

/// Assets for the seed bank and seed packets.
#[derive(Debug, AssetCollection, Resource)]
pub struct SeedBankAssets {
    /// Background of various seed packets.
    #[asset(texture_atlas(tile_size_x = 50., tile_size_y = 70., columns = 9, rows = 1))]
    #[asset(path = "seeds.png")]
    pub seed_packet_background: Handle<TextureAtlas>,
    /// Larger packet background, used in "card bonus" at the end of levels.
    ///
    /// Currently used in the seed bank, because we cannot yet use a [`TextureAtlas`] in
    /// [`ImageBundle`]s. Waiting for [bevyengine/bevy#5103] & [bevyengine/bevy#5070]
    /// (expected in 0.10.0).
    ///
    /// [bevyengine/bevy#5103]: https://github.com/bevyengine/bevy/pull/5103
    /// [bevyengine/bevy#5070]: https://github.com/bevyengine/bevy/pull/5070
    #[asset(path = "SeedPacket_Larger.png")]
    pub seed_packet_large: Handle<Image>,
    /// Silhouette of seed packets.
    #[asset(path = "SeedPacketSilhouette.png")]
    pub seed_packet_silhouette: Handle<Image>,
    /// Background of the seed bank.
    #[asset(path = "SeedBank.png")]
    pub seed_bank_background: Handle<Image>,
}

/// Plugin for the seed bank.
#[derive(Default, Debug, Copy, Clone)]
pub struct SeedBankPlugin;

impl Plugin for SeedBankPlugin {
    fn build(&self, app: &mut App) {
        app.insert_resource(GridInfo::default())
            .add_loading_state(LoadingState::new(AssetState::AssetLoading)
                .with_collection::<SeedBankAssets>()
                .continue_to_state(AssetState::AssetReady)
                .on_failure_continue_to_state(AssetState::LoadFailure))
            .add_system_set(SystemSet::on_enter(AssetState::AssetReady).with_system(spawn_seed_bank));
    }
}

/// Description of a seed bank.
#[derive(Debug, Copy, Clone, Component)]
pub struct SeedBank {
    packet_number: usize,
}

/// Marker for the first part of the background of the seed bank.
#[derive(Debug, Clone, Component)]
pub struct SeedBankBackgroundHead;

/// Marker for the middle parts of the background of the seed bank.
#[derive(Debug, Copy, Clone, Component)]
pub struct SeedBankBackgroundMiddle;

/// Marker for the last part of the background of the seed bank.
#[derive(Debug, Copy, Clone, Component)]
pub struct SeedBankBackgroundTail;

/// Marker of the rectangular area for seed packets in a seed bank.
#[derive(Debug, Copy, Clone, Component)]
pub struct SeedPacketArea;

/// Index of a seed packet.
#[derive(Debug, Copy, Clone, Component)]
pub struct SeedPacketIndex(usize);

#[derive(Copy, Clone, PartialEq, Resource)]
struct GridInfo {
    position: Vec2,
    bank_size: Vec2,
    packet_size: Vec2,
    natural_packet_count: usize,
    extension_packet_count: usize,
    padding_top_left: Vec2,
    separator: f32,
}

impl Default for GridInfo {
    fn default() -> Self {
        GridInfo {
            position: Vec2::new(230.0, 0.0),
            bank_size: Vec2::new(446.0, 87.0),
            packet_size: Vec2::new(50.0, 70.0),
            natural_packet_count: 7,
            extension_packet_count: 6,
            padding_top_left: Vec2::new(79.0, 7.0),
            separator: 1.0,
        }
    }
}

/// Seed packet content.
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum SeedPacket {
    /// Gray packet (generated by imitator).
    Gray,
    /// Purple packet (planted on other plants).
    Purple,
    /// Green packet (normal plants).
    Green,
    /// Crater recovery.
    Crater,
    /// Refresh game.
    Refresh,
    /// Sun packet.
    Sun,
    /// Diamond packet.
    Diamond,
    /// Snorkel zombie (in aquarium level).
    Snorkel,
    /// Trophy (goal in mini games).
    Trophy,
}

fn spawn_seed_bank(
    seed_bank_assets: Res<SeedBankAssets>,
    grid_info: Res<GridInfo>,
    mut commands: Commands,
) {
    let bank = commands.spawn((
        Name::new("SeedBank"),
        SeedBank { packet_number: 10 },
        NodeBundle {
            style: Style {
                position: UiRect {
                    left: Val::Px(grid_info.position.x),
                    top: Val::Px(grid_info.position.y),
                    ..default()
                },
                ..default()
            },
            ..default()
        },
    )).id();
    let bank_size = Size {
        width: Val::Px(grid_info.bank_size.x),
        height: Val::Px(grid_info.bank_size.y),
    };
    let head = commands.spawn((
        Name::new("SeedBankHead"),
        SeedBankBackgroundHead,
        ImageBundle {
            image: UiImage(seed_bank_assets.seed_bank_background.clone()),
            style: Style {
                position_type: PositionType::Absolute,
                position: UiRect {
                    left: Val::Px(0.0),
                    top: Val::Px(0.0),
                    ..default()
                },
                size: bank_size,
                ..default()
            },
            ..default()
        },
    )).id();
    let tail_offset = {
        let base = grid_info.padding_top_left.x;
        let delta = grid_info.natural_packet_count;
        let offset = (grid_info.packet_size.x + grid_info.separator) * (delta as f32);
        base + offset
    };
    let tail_internal_offset = {
        let base = grid_info.padding_top_left.x;
        let delta = grid_info.natural_packet_count - (10 - grid_info.natural_packet_count);
        let offset = (grid_info.packet_size.x + grid_info.separator) * (delta as f32);
        base + offset
    };
    // using a `NodeBundle` to clip the image
    // TODO: transition to the improved TextureAtlas API expected in Bevy 0.10
    let tail_container = commands.spawn(NodeBundle {
        style: Style {
            overflow: Overflow::Hidden,
            position_type: PositionType::Absolute,
            position: UiRect {
                left: Val::Px(tail_offset),
                ..default()
            },
            size: Size {
                width: Val::Px(grid_info.bank_size.x - tail_internal_offset),
                height: Val::Px(grid_info.bank_size.y),
            },
            ..default()
        },
        ..default()
    }).id();
    let tail = commands.spawn((
        Name::new("SeedBankTail"),
        SeedBankBackgroundTail,
        ImageBundle {
            image: UiImage(seed_bank_assets.seed_bank_background.clone()),
            style: Style {
                position: UiRect {
                    left: Val::Px(-tail_internal_offset),
                    ..default()
                },
                size: bank_size,
                min_size: bank_size,
                max_size: bank_size,
                ..default()
            },
            ..default()
        },
    )).id();
    commands.entity(bank).add_child(head).add_child(tail_container);
    commands.entity(tail_container).add_child(tail);
    let container = commands.spawn(NodeBundle {
        background_color: Color::NONE.into(),
        style: Style {
            flex_direction: FlexDirection::Row,
            position_type: PositionType::Absolute,
            position: UiRect {
                left: Val::Px(grid_info.padding_top_left.x),
                top: Val::Px(grid_info.padding_top_left.y),
                ..default()
            },
            ..default()
        },
        ..default()
    }).id();
    commands.entity(bank).add_child(container);
    commands.entity(container).with_children(|parent| for i in 0..10 {
        parent.spawn((
            ImageBundle {
                image: UiImage(seed_bank_assets.seed_packet_large.clone()),
                style: Style {
                    margin: UiRect {
                        right: Val::Px(grid_info.separator),
                        ..default()
                    },
                    size: Size {
                        width: Val::Px(grid_info.packet_size.x),
                        height: Val::Px(grid_info.packet_size.y),
                    },
                    ..default()
                },
                ..default()
            },
            SeedPacketIndex(i),
        ));
    });
}
