[package]
name = "reanim-decode"
version = "0.1.0"
edition = "2021"
authors = ["Xie Ruifeng <ruifengx@outlook.com>"]
repository = "https://github.com/ruifengx/librePvZ.git"
homepage = "https://github.com/ruifengx/librePvZ/tree/main/reanim-decode"
license = "AGPL-3.0-or-later"
readme = "README.md"
description = "decoder for PvZ reanim files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = { version = "0.8.23", optional = true }
serde_json = { version = "1.0.79", optional = true }
fern = { version = "0.6.0", optional = true, features = ["colored"] }
clap = { version = "3.1.5", optional = true, features = ["derive"] }
anyhow = { version = "1.0.55", optional = true }

[features]
default = ["yaml", "json"]
cli = ["dep:fern", "dep:clap", "dep:anyhow"]
yaml = ["dep:serde_yaml"]
json = ["dep:serde_json"]

[[bin]]
name = "reanim-decode"
required-features = ["cli"]
