[package]
name = "reanim-decode"
version = "0.1.0"
edition = "2021"
authors = ["Ruifeng Xie <ruifengx@outlook.com>"]
repository = "https://github.com/ruifengx/librePvZ.git"
homepage = "https://github.com/ruifengx/librePvZ/tree/main/reanim-decode"
license = "AGPL-3.0-or-later"
readme = "README.md"
description = "decoder for PvZ reanim files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
thiserror = "1.0.30"
log = "0.4.14"
flate2 = "1.0.22"
libre_pvz_resources = { path = "../libre_pvz_resources" }
bincode = "2.0.0-rc.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = { version = "0.8.23" }
serde_json = { version = "1.0.80" }
fern = { version = "0.6.0", optional = true, features = ["colored"] }
clap = { version = "3.1.18", optional = true, features = ["derive"] }
anyhow = { version = "1.0.55", optional = true }

[features]
cli = ["dep:fern", "dep:clap", "dep:anyhow", "libre_pvz_resources/serde"]

[[bin]]
name = "reanim-decode"
required-features = ["cli"]
