name: Build/Test/Doc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOC_PATH: target/doc

jobs:
  test:
    name: ${{ matrix.readable_os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          readable_os: Ubuntu
        - os: windows-latest
          readable_os: Windows
        - os: macos-latest
          readable_os: macOS
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Install ALSA and udev libraries (Linux)
      run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev libudev-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Clippy checks
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-features
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Install ALSA and udev libraries (Linux)
      run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev libudev-dev
    - name: Generate documentation
      run: cargo doc --all-features
    - name: Copy documentation index page
      run: cp .github/pages/index.html ${{ env.DOC_PATH }}
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
