name: Build/Test/Doc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOC_PATH: target/doc

jobs:
  test:
    name: ${{ matrix.readable_os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          readable_os: Ubuntu
        - os: windows-latest
          readable_os: Windows
        - os: macos-latest
          readable_os: macOS
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - uses: Swatinem/rust-cache@v1
    - name: Clippy checks
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        # currently warnings in local Bevy fork
        args: --all-features
        # args: -- -D warnings
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v1
    - name: Generate documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --all-features
    - name: Copy documentation index page
      run: cp .github/pages/index.html ${{ env.DOC_PATH }}
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
